# Generated by Django 4.1.5 on 2023-02-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_navigationmenu_alter_bookinstance_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigationtree", old_name="menu", new_name="nav_menu",
        ),
    ]
