# Generated by Django 4.1.5 on 2023-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_menu_navigationtree_nav_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationtree",
            name="name",
            field=models.CharField(
                default="Node of tree",
                help_text="Enter the name",
                max_length=300,
                verbose_name="Name",
            ),
        ),
    ]
