# Generated by Django 4.1.5 on 2023-02-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_navigationtree_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigationtree", options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="navigationtree",
            name="is_parent",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="navigationtree",
            name="nav_menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.navigationmenu",
            ),
        ),
        migrations.AlterField(
            model_name="navigationtree",
            name="parent",
            field=models.ForeignKey(
                default="#",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.navigationtree",
            ),
        ),
    ]
