# Generated by Django 4.1.5 on 2023-02-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_navigationtree_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationtree",
            name="is_parent",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
