# Generated by Django 4.1.5 on 2023-02-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_navigationtree_is_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationmenu",
            name="root_id",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
