# Generated by Django 4.1.5 on 2023-02-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_navigationmenu_root_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="navigationmenu", name="root_id",),
    ]
